sudo: required
language: java
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk11
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run -d -p 2181:2181 -p 9092:9092 -e ADVERTISED_HOST=127.0.0.1  -e NUM_PARTITIONS=3 johnnypark/kafka-zookeeper
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main