sudo: required
language: java
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk11
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: mvn clean install
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main